[book]
authors = ["Xiong Ding"]
language = "en"
src = "src"
title = "Life as a Programmer"

[output.html]
site-url = "/dev-notes/"
mathjax-support = true
additional-css = ["theme/code-details.css"]

[output.html.fold]
enable = true
level = 2
